### ISSUE TITLE
Configure secrets for the repo

### ISSUE THREAD

**Issue by bcessa** [algorandfoundation/did-algo#1]
In order to access some external private repositories and publish the project's artifacts (e.g., docker images), we need permissions to setup secrets in this repository. The secrets will be used by the CI workflows when running several tasks.

For example:

```yaml
- name: Set up runner environment
  run: ./.github/workflows/assets/utils.sh setup
  env:
      GITHUB_USER: ${{ github.actor }}
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
```

More information: [Github Container Registry](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry)
